### ISSUE TITLE
Not finding .exe files

### ISSUE THREAD

**Issue by bjsilver** [wrfchem-leeds/WRFotron#16]
I am getting a whole lot of errors during pre.bash when trying the default run with a clean version of WRFotron.

```bash

openmpi/3.1.4 conflicts with loaded module 'intelmpi/2019.4.243'
utility.c(742):WARN:60: Flush error on file 'stdout'
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 64: ungrib.exe: command not found
[proxy:0:0@d10s2b1.arc4.leeds.ac.uk] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:117): execvp error on file geogrid.exe (No such file or directory)
[proxy:0:0@d10s2b1.arc4.leeds.ac.uk] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:117): execvp error on file metgrid.exe (No such file or directory)
rm: cannot remove ‘FILE*’: No such file or directory
rm: cannot remove ‘namelist.input’: No such file or directory
[proxy:0:0@d10s2b1.arc4.leeds.ac.uk] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:117): execvp error on file real.exe (No such file or directory)
mv: cannot stat ‘rsl*’: No such file or directory
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 112: megan_bio_emiss: command not found
mv: cannot stat ‘wrfbiochemi_d01’: No such file or directory
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 124: ncatted: command not found
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 129: ncks: command not found
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 134: wesely: command not found
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 136: exo_coldens: command not found
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 145: anthro_emis: command not found
ln: failed to create symbolic link ‘./anthro_emis.inp’: File exists
cp: cannot stat ‘/nobackup/WRFChem/WRF_UoM_EMIT/WRF_UoM_EMIT/final_output’: No such file or directory
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 151: ncl: command not found
Traceback (most recent call last):
  File "sum_sector_emiss_wrfchemi.py", line 2, in <module>
    import xarray as xr
ModuleNotFoundError: No module named 'xarray'
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 160: fire_emis: command not found
[proxy:0:0@d10s2b1.arc4.leeds.ac.uk] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:117): execvp error on file real.exe (No such file or directory)
mv: cannot stat ‘rsl*’: No such file or directory
/var/spool/sge_prod/d10s2b1/job_scripts/699115: line 212: mozbc: command not found
cp: cannot stat ‘/nobackup/eebjs/simulation_WRFChem4.2_test/restart/base/wrfrst_d01_2016-10-12_00:00:00’: No such file or directory
cp: cannot stat ‘/home/home01/eebjs/github_wrfotron/WRFotron_githubclean/WRFotron/pp_concat_regrid.py’: No such file or directory
cp: cannot stat ‘/home/home01/eebjs/github_wrfotron/WRFotron_githubclean/WRFotron/pp_concat_regrid.bash’: No such file or directory
rm: cannot remove ‘met_em*’: No such file or directory
```

The errors relating to missing or conflicting modules seemed to be fixed by switching to '_manual' versions of config.bash and pre.bash (but while keeping `/nobackup/WRFChem/` instead of `/nobackup/{$USER}` 

But the errors about not finding executables remain. Where should these executables be? I can't see them in `/nobackup/WRFChem/` 
Maybe it would be better to have an absolute path constructed from variables in the bash scripts rather than using a relative path. But I'm not sure where the .exe files should come from when using the CEMAC version.

Thanks

**Comment by lukeconibear** [comment]
The module conflict at the start will stop the CEMAC executables from running properly. This would need a `module purge` if you have other modules loaded in the shell.

`ungrib.exe: command not found` happens in the manual version when the executable doesn't have `./` before it. This is not there for the CEMAC run, while it is there for the manual run. Hence, it makes sense that this works when you use the manual `pre.bash` file, though I'm not sure why this error is returned for the CEMAC run.

The paths in `config.bash.blueprint_manual` are examples, as the specific paths depend on where the user has placed everything. So for example, everything may not be in `/nobackup/${USER}`.

CEMAC uses pre-built executables, which for the default setup are in: `/nobackup/cemac/software/apps/WRFChem/4.2/1/intel-19.0.4-openmpi-3.1.4/bin`.

I just repeated a default clean test following the README instructions and everything worked fine.

You could always send me the path to your run.

**Comment by bjsilver** [comment]
Thanks for this Luke. I didn't realise that the executables files were not meant to be in the run folder in the CEMAC version of WRFotron. Seems to be working now that I removed the lines in my .bashrc that loaded modules that we used to need. Thanks

**Comment by lukeconibear** [comment]
Glad to hear this worked
