### ISSUE TITLE
netcdf error

### ISSUE THREAD

**Issue by chmltf** [wrfchem-leeds/WRFotron#21]
Hi, 
I recently started running WRFV4.2 (manually compiled) using the EDGARHTAP2-MEIC2015 anthro emissions files in the `/nobackup/WRFChem/` on ARC4. I have an error in my pre.bash.exxxx that reads the following:
```
Name of source model =>ECMWF                           
Name of source model =>ECMWF                           
Name of source model =>ECMWF                           
starting wrf task            0  of            1
ncks: INFO nco_fl_open() reports current extended filetype = NC_FORMATX_NC3 does not equal previous extended filetype = NC_FORMATX_HDF5. This is expected when NCO is instructed to convert filetypes, i.e., to read from one type and write to another. And when NCO generates grids or templates (which are always netCDF3) when the input file is netCDF4. It is also expected when multi-file operators receive files known to be of different types. However, it could also indicate an unexpected change in input dataset type of which the user should be cognizant.
Netcdf error
ln: failed to create symbolic link ‘./anthro_emis.inp’: File exists
Traceback (most recent call last):
  File "sum_sector_emiss_wrfchemi.py", line 11, in <module>
    if '00z' in wrfchemi_files[0]:
IndexError: list index out of range
 starting wrf task            0  of            1
```

I think this netcdf error might be causing problems with the anthro emis, the tail of the anthro_emis.out reads:

```
data_file_init: Initializing type for src emission file EDGARHTAP2_MEIC2015_CO_
 2010.0.1x0.1.nc
 data_file_init:  nlon_src, nlat_src =         3600        1800
 data_file_init: data_dx,dx,has_area_map =    11117.58       30000.00     T
 data_file_init: file EDGARHTAP2_MEIC2015_CO_2010.0.1x0.1.nc is a new grid
data_file_init: xcen_src(1,2)  =  -179.949996948242     -179.850006103516    
data_file_init: xedge(1,2) =  -179.999992370605     -179.900001525879    
data_file_init: dx =                     10
data_file_init: nlon_src,nlat_src =   3600   1800
data_file_init: ycen_src  =   89.8499984741211      89.9499969482422    
data_file_init: yedge_src =   89.8999938964844      89.9999961853027    
 ====================================================
 get_units: con_fac(1,2) =   3.6000000E+12  1.0000000E+09
 ====================================================
  
 next_flnm; trying to increment file EDGARHTAP2_MEIC2015_CO_2010.0.1x0.1.nc
 next_flnm; il, iu =           35          35
 next_flnm; file_number =            1
 next_flnm; new file = EDGARHTAP2_MEIC2015_CO_2010.0.1x0.0.nc
 data_file_timing_init : Failed to open 
 /nobackup/chmltf/WRFChem/emissions/EDGAR-HTAP2_MEIC2015/MOZART/EDGARHTAP2_MEIC2
 015_CO_2010.0.1x0.0.nc
 No such file or directory    

```
So it does find the emissions files, but for some reason for the next file is looking for  EDGARHTAP2_MEIC2015_CO_2010.0.1x**0.0**.nc, which I do not understand.

Here is my module list:

```
  1) licenses              3) intel/19.0.4          5) intelmpi/2019.4.243   7) ncl/6.5.0             9) wrfchemconda/3.7
  2) sge                   4) user                  6) netcdf/4.6.3          8) nco/4.6.0
```

**Comment by lukeconibear** [comment]
Hi Lauren,

Thanks for posting this issue here.

This iteration error is a generic outcome (and unhelpful diagnostic) of `anthro_emis` failing to process an emission file. I have seen this same error resulting from many different causes, including:

1. `data_yrs_offset` not being set correctly within `anthro_emis.inp`.
2. Incorrect `date` variable within the emission inventory.
3. No units in the emission variables. 
4. Emission files are not readable/executable by the group/all users.
5. Runs beginning in December (instead need to start the run at an earlier time and run through the bad section i.e. start in Nov). 
6. Not starting the run on the 1st of the month.

The emissions in `/nobackup/WRFChem/emissions/EDGAR-HTAP2_MEIC2015` have been tested successfully, so I think issues 2, 3, and 4 should not be a problem.

So this problem could be caused by 1, 5, or 6 (or something else).
 - Is your `data_yrs_offset` equal to the run year minus the emission inventory year (e.g. for a 2015 run with these merged EDGARHTAP2 emissions that are based on 2010, `data_yrs_offset` would be 5)?
- Is your run beginning in December?
- Or is it starting on a day of the month that isn't the 1st?

**Comment by chmltf** [comment]
Hi Luke,

Thanks. This was helpful. I was starting my run on 4 Dec 2016. I reran on 4 Nov 2016, and anthro_emis runs successfully. 
I am still getting the netcdf error:
```
ncks: INFO nco_fl_open() reports current extended filetype = NC_FORMATX_NC3 does not equal previous extended filetype = NC_FORMATX_HDF5. This is expected when NCO is instructed to convert filetypes, i.e., to read from one type and write to another. And when NCO generates grids or templates (which are always netCDF3) when the input file is netCDF4. It is also expected when multi-file operators receive files known to be of different types. However, it could also indicate an unexpected change in input dataset type of which the user should be cognizant.
Netcdf error
```
in my pre.bash.exxx. And some problems finding variables in mozbc_bc.log, and failure in the diurnal_emis.out. But I think this is due to changing the mechanism chem_opt = 202 and emis_opt = 11. I am running again with chem_opt = 202 and emis_opt = 10 and will let you know if this netcdf error persists.

**Comment by lukeconibear** [comment]
That's good to hear that `anthro_emis` is running okay now.

That netcdf error is from the `ncks` call. In `pre.bash`, `ncks` is only called once to merge the `Times` variable between the `wrfinput` files and the `wrfbiochemi` files. WRFChem versions after 4.0 use NETCDF4 (built on HDF5), while WRFChem versions before 4.0 use NETCDF3. So here, your WRFChem4.2 will create NETCDF4 files and I think the older megan_bio_emiss preprocessor created NETCDF3 files. This would cause that error message saying that these different file formats cannot be merged. 

It doesn't appear that the [bio_emiss](https://www.acom.ucar.edu/wrf-chem/download.shtml) preprocessor has been updated to output NETCDF4 files. 

The solution to this that I've done is to add the following flag to the `namelist.wrf.blueprint` within the `&time_control` section. Do you have this flag?
```bash
force_use_old_data                  = T,        ! allow WRFChem4 to run with data from WRFChem3
```

If those other problems persist with `mozbc_bc.log` and `diurnal_emis.out`, let me know.

I assume your testing the MOZCART/MOZCART-T1 schemes. It would be good to have the process to changing to these options documented, so once things are working please let me know.

**Comment by chmltf** [comment]
Okay thanks. This is good info. I do have this flag.
```
force_use_old_data                  = T,                                              ! allow WRFChem4 to run with data from WRFChem3
 /
```
Unfortunately I still see that netcdf error. 

With chem_opt=202 and emis_opt = 10, mozbc is fine now. Although there is a problem with the diurnal emissions.
The tail of the diurnal_emiss.out.
```
(0)     == Using single layered emission files. ==
(0)     == Creating new emission files ==
(0)     ==== Preparing the emission files ====
(0)     == Emission source files not accessible, failure in emission_file_setup, check these paths:
(0)     /nobackup/chmltf/simulation_WRFChem4.2_test_CHEMOPT202/run/base/2016-11-03_00:00:00-2016-11-10_18:00:00/wrfchemi_00z_d02
(0)     /nobackup/chmltf/simulation_WRFChem4.2_test_CHEMOPT202/run/base/2016-11-03_00:00:00-2016-11-10_18:00:00/wrfchemi_12z_d02
processing /nobackup/chmltf/simulation_WRFChem4.2_test_CHEMOPT202/run/base/2016-11-03_00:00:00-2016-11-10_18:00:00/wrfchemi_00z_d01
writing updated /nobackup/chmltf/simulation_WRFChem4.2_test_CHEMOPT202/run/base/2016-11-03_00:00:00-2016-11-10_18:00:00/wrfchemi_00z_d01
processing /nobackup/chmltf/simulation_WRFChem4.2_test_CHEMOPT202/run/base/2016-11-03_00:00:00-2016-11-10_18:00:00/wrfchemi_12z_d01
writing updated /nobackup/chmltf/simulation_WRFChem4.2_test_CHEMOPT202/run/base/2016-11-03_00:00:00-2016-11-10_18:00:00/wrfchemi_12z_d01
```
I cannot find anything with d02 in the MAIN_emission_processing.ncl (or anywhere else), so I'm not sure why it looks for that instead of d01 first.

**Comment by lukeconibear** [comment]
Okay. Did `megan_bio_emiss` run successfully and do the `wrfbiochemi` files have the `Times` variable? If so, then this may not be an issue.

So the `mozbc` issue is specific to MOZCART-T1. Maybe Mary or online has the required namelist mapping (`mozbc.inp`) for this scheme?

So that looks like the diurnal cycle was fine for `d01`, but failed for `d02` as the `wrfchemi_00/12z_d02` files don't exist. Assuming you're running with a single domain, this is okay.

On line 39 of `MAIN_emission_processing.ncl` the `domains` are set as:
```ncl
domains = (/"d01","d02","d03"/)
```
You could remove `d02` and `d03` from this if you wish, though add them back if you ever run with nests.

I once planned on rewriting these NCL scripts using python as NCL is depreciated, though I've abandoned that idea now.

**Comment by chmltf** [comment]
I think that wrfbiochemi_d01 was built successfully. When I looked at the file for my other runs the headers looked the same (see below).

```
[chmltf@login1.arc4 2016-11-03_00:00:00-2016-11-10_18:00:00]$ ncdump -h wrfbiochemi_d01
netcdf wrfbiochemi_d01 {
dimensions:
        west_east = 139 ;
        south_north = 139 ;
        months_per_year_stag = 12 ;
        DateStrLen = 19 ;
        Time = UNLIMITED ; // (1 currently)
variables:
        char Times(Time, DateStrLen) ;
        float XLONG(Time, south_north, west_east) ;
                XLONG:MemoryOrder = "XY " ;
                XLONG:description = "LONGITUDE, WEST IS NEGATIVE" ;
                XLONG:units = "degree east" ;
                XLONG:stagger = "" ;
                XLONG:FieldType = 104 ;
```
Okay, got it, thanks. Glad the diurnal_emiss is fine then.

Thanks, I will look for another mozbc.inp file specific to the species in the mechanism. And will definitely update you on implementing the new mechanism when I get everything ironed out.

**Comment by lukeconibear** [comment]
Okay, this all sounds good.

By the way, you can check the diurnal cycle was applied to the `wrfchemi` files using `python plot_wrfchemi.py` from the run folder. This should loop through the emissions and produce similar images to this (if the diurnal cycle failed, then these bars would all be equal):
![image](https://user-images.githubusercontent.com/19871268/99877313-1f79f400-2bf5-11eb-8a59-d08197fdc443.png)

**Comment by chmltf** [comment]
Thanks for this tip!
