### ISSUE TITLE
pp_concat_regrid.bash not concatenating output- giving a key error associated with the word "longitude"

### ISSUE THREAD

**Issue by EECJC17** [wrfchem-leeds/WRFotron#27]
Hi

I've been trying to do a test run of WRF-Chem, but I can't get pp_concat_regrid.bash to concatenate the hourly output files. My test run is a single day - 2016 10 12 00 24 06 using an automatic simulation.

My submission ends early and I just get a pp_concat_regrid.bash.e* file and a pp_concat_regrid_bash.o* file. I think the issue is something to do with the variable names, but I'm not really sure how to translate the error or where I'd look to fix it. I got the following error in pp_concat.regrid.bash.e*:
Traceback (most recent call last):
     File "home/home01/eecjc/miniconda3/envs/python3_ncl_nco/lib/python3.8/site-packages/xarray/core/dataarray.py". line 687, in _getitem_coord
var = self.coords[key]
KeyError = 'longitude'

It then gives me further errors that also seem to be something to do with the key/variable being called 'longitude' including "DataArray.cf does not understand the key 'longitude'" and "ValueError('dataset must include lon/lat')

I am loading miniconda from my home folder and I am trying to use an environment I created this way:

conda create -n python3_ncl_nco -c conda-forge xarray salem xesmf numpy scipy pandas matplotlib rasterio affine ncl nco wrf-python dask geopandas descartes

If it helps, this is the full error: 
![image](https://user-images.githubusercontent.com/75302097/108091946-1b366900-7074-11eb-960f-f3496b691c1e.png)

I tried reducing the number of domains in pp_regrid_concat.py and resubmitting as I am only running with 1 domain, but got the same issue.

I'm not really used to Unix or using Arc, so apologies if this is a fairly garbled description or something I should be able to sort easily.

Cheers

Connor

**Comment by lukeconibear** [comment]
Hi Connor,

Thanks for posting this issue here.

I think the issue is with your conda environment.

1. Can you try using the CEMAC conda environment?
First, you'll have to unload your personal conda and remove it from `pp_concat_regrid.bash`. Then, load the CEMAC conda. Then resubmit.

```bash
conda deactivate # once for python3_ncl_nco
conda deactivate # once or base

gedit pp_concat_regrid.bash
# remove conda activate python3_ncl_nco

module load wrfchemconda/3.7

qsub pp_concat_regrid.bash
```

2. If this fails, then you could try creating a new personal conda environment based on 
[python3_ncl_nco.yml](https://github.com/wrfchem-leeds/WRFotron/blob/master/namelists/python3_ncl_nco.yml), that I've just added.
First delete the old environment. Then create the new one based on the `.yml` file.
```bash
conda remove --name python3_ncl_nco --all

conda env create --name python3_ncl_nco --file=python3_ncl_nco.yml
```

**Comment by EECJC17** [comment]
Hi Luke

Thanks for the help!

I think this has helped get past that issue - I'm now getting another error talking about "setting the environmental variable PROJ_LIB". I've been having a look at getting around that, but I'm not having any luck. Googling it, it seems to be something to do with Basemap, but it seems to be unhappy with whichever module it tries to import first. The error looks like this:

![image](https://user-images.githubusercontent.com/75302097/108190276-a3b31900-7109-11eb-9a3c-312cc562e244.png)

I've tried a suggestion I found on the internet, so now my pp_concat_regrid.py looks like this: 
![image](https://user-images.githubusercontent.com/75302097/108190378-c5ac9b80-7109-11eb-942a-73cb77542a17.png) but I still got the same error.

My pp_concat_regrid.bash file looks like this: 
![image](https://user-images.githubusercontent.com/75302097/108190449-dc52f280-7109-11eb-8ae1-13d25ebb71cb.png)
Nothing seems to happen when I call . /nobackup/cemac/cemac.sh, so I tried putting it in the bash file and it doesn't seem to change anything. I also tried putting in the full path to the wrfchem conda 

I also tried your second suggestion, but it didn't seem to want to let me either use conda env create from the yml file, or to get the yml file from git first (git clone https://github.com/wrfchem-leeds/WRFotron/blob/master/namelists/python3_ncl_nco.yml/' gives me "repository not found'). I'm hesitant to try to update WRFotron now as it'd take me a while to set up all the different things I'd need in config.bash etc and I could really do with some output I can analyse soon.

**Comment by lukeconibear** [comment]
I think `pp_concat_regrid.bash` should just need:
```bash
module load wrfchemconda/3.7
python pp_concat_regrid.py
```

I copied your `wrfout` files and if I removed `reuse_weights=True` from [line 37](https://github.com/wrfchem-leeds/WRFotron/blob/master/pp_concat_regrid.py#L37), then this worked.

You shouldn't need to add those lines at the top of `pp_concat_regrid.py`.

If this doesn't work, then let me when is returned when you type:
```bash
module list
python
```

**Comment by EECJC17** [comment]
I got the same error unfortunately - I'm guessing I've not loaded something in properly. This is what I get from typing those commands into the terminal:

[eecjc@login2.arc4 base]$ module list
Currently Loaded Modulefiles:
  1) licenses        2) sge             3) intel/19.0.4    4) openmpi/3.1.4   5) user
[eecjc@login2.arc4 base]$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by lukeconibear** [comment]
Yes, you also need to have the CEMAC conda module loaded (`module load wrfchemconda/3.7`) in the terminal you submit from (`qsub pp_concat_regrid.bash`).

**Comment by EECJC17** [comment]
Ah, oops! Apologies for the daft questions.

Quick question - does wrfchemconda/3.7 load xarray? I'm now getting a module not found error. I had a look in the wrfchemconda folder and it doesn't seem to tell me

**Comment by lukeconibear** [comment]
No worries.

The module `wrfchemconda/3.7` is a Python environment. This environment has `xarray` installed, but nothing is loaded by default. The first line of `pp_concat_regrid.py` tries to load `xarray`. If this fails, then the module is not loaded properly. I would recommend following the steps below to ensure you load the correct modules.

```bash
[earlacoa@login2.arc4 earlacoa]$ module purge
[earlacoa@login2.arc4 earlacoa]$ module list
No Modulefiles Currently Loaded.
[earlacoa@login2.arc4 earlacoa]$ module load intel/19.0.4 openmpi/3.1.4 netcdf/4.6.3 WRFchem/4.2 ncl/6.5.0 nco/4.6.0 wrfchemconda/3.7 sge
[earlacoa@login2.arc4 earlacoa]$ python
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xarray as xr
>>> 

```

**Comment by lukeconibear** [comment]
This issue is now resolved.

Note, I've updated [`pp_concat_regrid.py`](https://github.com/wrfchem-leeds/WRFotron/blob/master/pp_concat_regrid.py) so the weight reuse should also work now.
