### ISSUE TITLE
Changing wrfbiochemi file for ingestion into WRFChem not working

### ISSUE THREAD

**Issue by cm17nav** [wrfchem-leeds/WRFotron#30]
**What happened**:
My run with an altered `wrfbiochemi_domain_{projectTag}` file is not working. The run stopped during `pre.bash`: the message at the end of pre.bash.e was

`rm: cannot remove 'namelist.input': No such file or directory`
` starting wrf task            0  of            1`
` starting wrf task            0  of            1`
--------------------------------------------------------------------------
`MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD`
`with errorcode 1.`

`NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.`
`You may or may not see output from other processes, depending on`
`exactly when Open MPI kills them.`
--------------------------------------------------------------------------
` in module_wrfchem_lib ...`
`cp: cannot stat '/nobackup/cm17nav/simulation_WRFChem4.2_b1/restart/base/wrfrst_d01_2015-06-01_00:00:00': No such file or directory`

In my WRFotron's pre.bash, I commented out lines 107-129. 

(I am not sure whether this is helpful or not: `rsl.error.0000` had an error message at the end, which was

`FATAL CALLED FROM FILE:  <stdin>  LINE:     314`
`Possibly missing file for = auxinput6`)

The path to my WRFotron is `/nobackup/cm17nav/WRFotron2.3.0_WRFChem4.2_b1`.
The path to my simulation folder is `/nobackup/cm17nav/simulation_WRFChem4.2_b1`.

**What you expected to happen**:
The altered `wrfbiochemi_domain_{projectTag}` file to be incorporated into WRFChem when `pre.bash` lines 107-129 were commented out.

**Comment by lukeconibear** [comment]
It looks like it first broke at `second_real_out/rsl.error.0000`, where the error at the end says:
```bash
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:    2529
 med_read_wrf_chem_bioemissions: error opening wrfbiochemi_d01
```
So, it wasn't able to open the `wrfbiochemi_d01` file.
Could you try without commenting out lines 107-129 in `pre.bash`? 
The if statement on lines [107-117](https://github.com/wrfchem-leeds/WRFotron/blob/master/pre.bash#L107-L117) shouldn't be run, as this is only if the `wrfbiochemi_d01` doesn't exist.
However, I think the for loop on lines [119-129](https://github.com/wrfchem-leeds/WRFotron/blob/master/pre.bash#L119-L129) might be needed to set the correct `START_DATE` and `SIMULATION_START_DATE`.

**Comment by cm17nav** [comment]
Thank you, that looks like it's done the trick

**Comment by lukeconibear** [comment]
Great, glad to hear!
