### ISSUE TITLE
Anthro emissions don't work when starting simulation in December

### ISSUE THREAD

**Issue by EECJC17** [wrfchem-leeds/WRFotron#41]
Hi
 
I remember from the last issue I posted here that anthro emissions don't work too well in simulations that start in December. I was just wondering if there's a way around it? I've been running a few months simulation in 1-2 week chunks, which worked fine for October & November, but the run doesn't seem to want to continue into December. I checked using grep -i and it's definitely the anthro emissions that aren't working. It's not a huge issue right now, but thought I should ask for future reference.

I'm using WRF-Chem 4.2 and a default version of WRFotron with the domain switched to Europe.

Cheers

Connor

**Comment by lukeconibear** [comment]
Anthropogenic emissions vary only by month and `anthro_emis` assigns the dates for the `wrfchemi*` files as the first day of the month. This means that `anthro_emis` crashes for simulation start times other than December 1st. The workaround is to start the simulation on December 1st, either for the whole month (e.g., `. master.bash 2015 12 01 00 744 00` using `main_restart.bash` if needed) or for 1-2 week chunks and copying the `wrfchemi*` files to the later simulation folders.
