### ISSUE TITLE
pp_concat_regrid.bash loading the right module

### ISSUE THREAD

**Issue by bjsilver** [wrfchem-leeds/WRFotron#47]
Hi Luke and Helen. Sorry I can't work this one out. @ailishgraham and I are instructing some MRes students on WRF-Chem and WRFotron, and I am writing some instructions on how to post process the output, and have been going through the process myself. 

https://github.com/wrfchem-leeds/WRFotron/blob/75d01ed5dec205bd2196e8e183e76424732e6162/pp_concat_regrid.bash#L7-L13

Even after I load the cemac module by running `. /nobackup/cemac/cemac.sh`, the output of  `((module list -t) |& grep -i wrfchemconda | wc -c)` is still 0 for some reason, so then the script tries to activate the conda environment `python3_ncl_nco` which I do not have, which results in an error.

If I do this
```bash
(base) [eebjs@login2.arc4 ~]$ conda deactivate
[eebjs@login2.arc4 ~]$ module purge
[eebjs@login2.arc4 ~]$ . /nobackup/cemac/cemac.sh
[eebjs@login2.arc4 ~]$ module list
No Modulefiles Currently Loaded.
[eebjs@login2.arc4 ~]$
```
I end up with no module files, not sure if I have done it right?

In my own runs, I got around this by editing `pp_concat_regrid.bash` so that it loaded my own python environment with the correct modules. But for instructing the MRes students I'd prefer to understand how to load and use the CEMAC modules correctly. Any advice on how to get this to work?  Which of the CEMAC modules need to be loaded for this script to work?

**Comment by lukeconibear** [comment]
Hey,
`. /nobackup/cemac/cemac.sh` just makes the CEMAC modules available, it doesn't load any of them. So, if you run `module avail` you'll see the CEMAC modules now available at the top. The CEMAC conda module can then be loaded via `module load wrfchemconda/3.7 `.

In your example in that terminal, you don't have either the CEMAC conda module loaded or a personal conda environment named `python3_ncl_nco`. So, the `if` statement is skipped, and the `else` statement returns an error.

In general, the user would submit this `pp_conat_regrid.bash` script from a terminal that was used for a WRFChem run. In that terminal, all the required modules would have been loaded from [`config.bash`](https://github.com/wrfchem-leeds/WRFotron/blob/master/config.bash#L7).

For new users, I would recommend using the CEMAC conda environment on ARC4 to abstract away the complexity of creating their own conda environment. This has all the libraries they'll need for standard analyse (e.g., numpy, xarray, pandas, etc.).

**Comment by bjsilver** [comment]
Thanks Luke, I get it now. Also I realised that stuff being loaded in my .bashrc was unloading the cemac module which was preventing the script from working as intended. Thanks!
