### ISSUE TITLE
PM emissions not being processed properly in anthro_emis

### ISSUE THREAD

**Issue by earagr** [wrfchem-leeds/WRFotron#48]
I just noticed there may be a problem within anthro_emis while using the default set-up. I get no PM emissions in the generated wrfchemi files. I think this may be because there are no units for the variables in the input files for POM, OIN_PM2.5 and PM2.5_PM10 (kg m-2 s-1) so the scaling factors can't be applied in mozbc:

ncdump -h /nobackup/WRFChem/emissions/EDGAR-HTAP2_MEIC2015/MOZART/EDGARHTAP2_MEIC2015_POM_2010.0.1x0.1.nc
netcdf EDGARHTAP2_MEIC2015_POM_2010.0.1x0.1 {​​​
dimensions:
        time = 12 ;
        lat = 1800 ;
        lon = 3600 ;
variables:
        float emis_tot(time, lat, lon) ;
                emis_tot:_FillValue = NaNf ;
        float lat(lat) ;
                lat:_FillValue = NaNf ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:comment = "center_of_cell" ;
        float lon(lon) ;
                lon:_FillValue = NaNf ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:comment = "center_of_cell" ;

data_file_init: Initializing type for src emission file EDGARHTAP2_MEIC2015_OIN
 _PM2.5_2010.0.1x0.1.nc

 data_file_init:  nlon_src, nlat_src =         3600        1800
 data_file_init: data_dx,dx,has_area_map =    11117.58       30000.00     T
 ====================================================
 get_units: con_fac(1,2) =   0.0000000E+00  0.0000000E+00
 ====================================================
  

I don't know if it will affect everyone but I had the same issue previously and found it was solved by adding units to each variable.

**Comment by lukeconibear** [comment]
I'm doing a test now.
I think that if no units are set then `anthro_emis` defaults to kg m-2 s-1, which should be right ([reference](https://groups.google.com/a/ucar.edu/g/wrf-chem-anthro_emiss/c/CHhC5En2Wag/m/Y88y9T9-AgAJ)).
What do you mean by scaling factor for `mozbc`?

**Comment by lukeconibear** [comment]
Excellent spot!

So, that forum post isn't right. If the units attribute is not there, then the conversion factor sets to 0, which effectively removes those emissions.
Testing with the units attribute added in, sets the conversion factor correctly, and therefore has the emissions.
This was very likely the cause of your issue.

I have fixed the default emissions in `/nobackup/WRFChem/emissions/EDGAR-HTAP2_MEIC2015/MOZART` and updated the [user guide](https://wrfchem-leeds.github.io/WRFotron/faqs.html) explaining this step.

Sorry this bug has caused you issues and thanks for reporting it here.
