### ISSUE TITLE
auxinput5=wrfchemi_<hr>z_d<domain>, error : Possibly missing file for = auxinput5

### ISSUE THREAD

**Issue by liy25** [wrfchem-leeds/WRFotron#55]
i have already get wrfchemi_00z_d01and wrfchemi_12z_d01 file, then i set 'auxinput5=wrfchemi_<hr>z_d<domain>' in namelist.input, and run wrf.exe. there are somes problems, error cannot resd file for auxinput5.
could you help me to resolve it ? thanks a lot!!

**Comment by zhu13142** [comment]
Did you solve the problem? I had the same problem? How did you solve it? I'm very confused about this problem now, thanks
