### ISSUE TITLE
Issue with regridding wrfoutput using 'regrid_wrfout.py' script

### ISSUE THREAD

**Issue by ailishgraham** [wrfchem-leeds/WRFotron#8]
When running the regrid_wrfout.py script I keep getting an error which I can't find any online help for (see below). It seems to occur when writing the regridded output to the new netcdf. I wondered if anyone has seen this before? I have checked the output to ensure there isn't an issues with the files that were concatenated. 

<CF Field: PM2_5_DRY(time(744), atmosphere_sigma_coordinate(32), latitude(404), longitude(492)) ug m^-3> netCDF: PM2_5_DRY_e
Traceback (most recent call last):
  File "regrid_wrfout.py", line 66, in <module>
    cf.write([var_010], 'wrfout_2019_oct_chemopt202_cf_regrid_pm25.nc', verbose=True, fmt='NETCDF4')
  File "/nfs/see-fs-01_teaching/ee15amg/anaconda2/envs/esmpy/lib/python2.7/site-packages/cf/write.py", line 283, in write
    HDF_chunks=HDF_chunksizes, unlimited=unlimited)
  File "/nfs/see-fs-01_teaching/ee15amg/anaconda2/envs/esmpy/lib/python2.7/site-packages/cf/netcdf/write.py", line 428, in write
    _write_a_field(f, g=g)
  File "/nfs/see-fs-01_teaching/ee15amg/anaconda2/envs/esmpy/lib/python2.7/site-packages/cf/netcdf/write.py", line 2209, in _write_a_field
    g=g)
  File "/nfs/see-fs-01_teaching/ee15amg/anaconda2/envs/esmpy/lib/python2.7/site-packages/cf/netcdf/write.py", line 1836, in _create_netcdf_variable
    raise NetCDFError(message)
cf.netcdf.write.NetCDFError: Can't create variable in NETCDF4 file from PM2_5_DRY field summary
-----------------------
Data           : PM2_5_DRY(time(744), atmosphere_sigma_coordinate(32), latitude(404), longitude(492)) ug m^-3
Axes           : atmosphere_sigma_coordinate(32) = [0.996500015259, ..., 0.0039653792046]
               : latitude(404) = [-49.553848, ..., -9.253848] degrees_north
               : longitude(492) = [129.41962, ..., 178.51962] degrees_east
               : time(744) = [2019-10-01T00:00:00Z, ..., 2019-10-31T23:00:00Z] standard
Coord refs     : <CF CoordinateReference: atmosphere_sigma_coordinate>
 (NetCDF: Bad chunk sizes.)

**Comment by lukeconibear** [comment]
Is this referring to [`wrfout_regrid.py`](https://github.com/wrfchem-leeds/python-scripts/blob/master/wrfout_regrid.py)? I assume that it is, and have therefore also assigned Ben to this issue, as he wrote that script.

Alternatively, you could use just the regridding code from [`wrfout_concat_regrid.py`](https://github.com/wrfchem-leeds/python-scripts/blob/master/wrfout_concat_regrid.py) (which I wrote as an alternative). For example, this would be something like:

```python
import xarray as xr
import salem
import xesmf as xe
import numpy as np

path = '...'

# open the dataset using xarray
with xr.open_dataset(path + '/file.nc') as ds:
    wrf = ds['PM2_5_DRY']

# or use salem instead, which can handle the staggered wrf variables nicely
with salem.open_wrf_dataset(path + '/file.nc') as ds:
    wrf = ds['PM2_5_DRY']

# set up the global grid and regridder
res = 0.25
global_grid = xr.Dataset({'lat': (['lat'], np.arange(-60, 85, res)), 'lon': (['lon'], np.arange(-180, 180, res)),})
regridder = xe.Regridder(wrf, global_grid, 'bilinear', reuse_weights=True)

# regrid the wrf variable to this global grid and clean the regridder if not reusing
wrf_regrid = regridder(wrf)
regridder.clean_weight_file()

# save new file
wrf_regrid.to_netcdf(path + '/file_regrid.nc')
```

**Comment by ailishgraham** [comment]
I think it's using an older version - the one we used in the WRF-Chem course you taught. I think I have identified the issue and found a fix - the max lons/lats in my domain had changed slightly and these are defined in the script so it was causing it to break. The error message just wasn't very helpful to find this out. Thanks for the help, and sorry - should have spotted this sooner!

**Comment by lukeconibear** [comment]
Great, no worries, thanks for sharing the solution.

I'll close this issue.
